"""Shared pytest fixtures for perf-mcp tests.

Provides:
    executor: A PerfExecutor instance for testing subprocess execution.
    perf_data: Path to a small test perf.data fixture file. Skips tests
        if the fixture is not present (it is generated by perf record
        and may not exist in CI environments without perf installed).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from perf_mcp.executor import PerfExecutor

FIXTURES_DIR = Path(__file__).parent / "fixtures"
TEST_PERF_DATA = FIXTURES_DIR / "test.perf.data"


@pytest.fixture
def executor() -> PerfExecutor:
    return PerfExecutor()


@pytest.fixture
def perf_data() -> str:
    if not TEST_PERF_DATA.exists():
        pytest.skip("test.perf.data fixture not found")
    return str(TEST_PERF_DATA)
